"""empty message

Revision ID: b0a8b40421d5
Revises: 658b1650d98c
Create Date: 2025-12-12 19:04:36.675003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a8b40421d5'
down_revision = '658b1650d98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('PHOTO', 'VIDEO', name='typemedia', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('PHOTO', 'VIDEO', name='typemedia', native_enum=False),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
